// Code generated by "stringer -type=Authentication"; DO NOT EDIT.

package scanner

import "strconv"

const _Authentication_name = "AU_ANONAU_DHEAU_DSSAU_ECCPWDAU_ECDSAAU_EXPORTAU_KEAAU_KRB5AU_KRB5_EXPORTAU_NULLAU_PSKAU_RSAAU_RSA_EXPORTAU_RSA_EXPORT_1024AU_RSA_FIPSAU_SHAAU_VKO_GOST_R_34_10_2001AU_VKO_GOST_R_34_10_94"

var _Authentication_index = [...]uint8{0, 7, 13, 19, 28, 36, 45, 51, 58, 72, 79, 85, 91, 104, 122, 133, 139, 163, 185}

func (i Authentication) String() string {
	if i < 0 || i >= Authentication(len(_Authentication_index)-1) {
		return "Authentication(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Authentication_name[_Authentication_index[i]:_Authentication_index[i+1]]
}
