// Code generated by "stringer -type=Authentication"; DO NOT EDIT.

package scanner

import "fmt"

const _Authentication_name = "AU_ANONAU_DSSAU_ECDSAAU_KEAAU_KRB5AU_KRB5_EXPORTAU_NULLAU_PSKAU_RSAAU_RSA_EXPORTAU_RSA_EXPORT_1024AU_RSA_FIPSAU_SHAAU_VKO_GOST_R_34_10_2001AU_VKO_GOST_R_34_10_94"

var _Authentication_index = [...]uint8{0, 7, 13, 21, 27, 34, 48, 55, 61, 67, 80, 98, 109, 115, 139, 161}

func (i Authentication) String() string {
	if i < 0 || i >= Authentication(len(_Authentication_index)-1) {
		return fmt.Sprintf("Authentication(%d)", i)
	}
	return _Authentication_name[_Authentication_index[i]:_Authentication_index[i+1]]
}
