// Code generated by "stringer -type=Encryption"; DO NOT EDIT.

package scanner

import "fmt"

const _Encryption_name = "ENC_3DES_EDE_CBCENC_AES_128_CBCENC_AES_128_GCMENC_AES_256_CBCENC_AES_256_GCMENC_CAMELLIA_128_CBCENC_CAMELLIA_256_CBCENC_DES40_CBCENC_DES_CBCENC_DES_CBC_40ENC_FORTEZZA_CBCENC_GOST28147ENC_IDEA_CBCENC_NULLENC_RC2_CBC_40ENC_RC2_CBC_56ENC_RC4_128ENC_RC4_40ENC_RC4_56ENC_SEED_CBCENC_CHACHA20_POLY1305_256"

var _Encryption_index = [...]uint16{0, 16, 31, 46, 61, 76, 96, 116, 129, 140, 154, 170, 183, 195, 203, 217, 231, 242, 252, 262, 274, 299}

func (i Encryption) String() string {
	if i < 0 || i >= Encryption(len(_Encryption_index)-1) {
		return fmt.Sprintf("Encryption(%d)", i)
	}
	return _Encryption_name[_Encryption_index[i]:_Encryption_index[i+1]]
}
