// Code generated by "stringer -type=Mac"; DO NOT EDIT.

package scanner

import "strconv"

const _Mac_name = "MAC_GOST28147MAC_GOSTR3411MAC_MD5MAC_NULLMAC_SHAMAC_SHA256MAC_SHA384"

var _Mac_index = [...]uint8{0, 13, 26, 33, 41, 48, 58, 68}

func (i Mac) String() string {
	if i < 0 || i >= Mac(len(_Mac_index)-1) {
		return "Mac(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Mac_name[_Mac_index[i]:_Mac_index[i+1]]
}
