// Code generated by "stringer -type=Protocol"; DO NOT EDIT.

package scanner

import "fmt"

const _Protocol_name = "PROT_SSLPROT_TLS"

var _Protocol_index = [...]uint8{0, 8, 16}

func (i Protocol) String() string {
	if i < 0 || i >= Protocol(len(_Protocol_index)-1) {
		return fmt.Sprintf("Protocol(%d)", i)
	}
	return _Protocol_name[_Protocol_index[i]:_Protocol_index[i+1]]
}
